In [0]:
%sql
select 4/2;

(4 / 2)
2.0

In [0]:
data =[(1,'Ram','Singh',2000,500),(2,'Shyam','Rawat',10000,700),(3,'Mohan','Kumar',3000,300)]
sch=['id','firstname','lastname','salary','bonus']
df=spark.createDataFrame(data,sch)
display(df)

id,firstname,lastname,salary,bonus
1,Ram,Singh,2000,500
2,Shyam,Rawat,10000,700
3,Mohan,Kumar,3000,300

In [0]:
#42. map ()-- tranformation of RDD used to apply function(lambda)on every element of RDD and returns a new RDD
# Dataframe doesnt have map() transformation, so u need to generate RDD first

data =[(1,'Ram','Singh',2000,500),(2,'Shyam','Rawat',10000,700),(3,'Mohan','Kumar',3000,300)]
rdd=spark.sparkContext.parallelize(data)
print(rdd.collect())
rdd1=rdd.map(lambda x : x + (x[1] + ' ' + x[2],))
print(rdd1.collect())

[(1, 'Ram', 'Singh', 2000, 500), (2, 'Shyam', 'Rawat', 10000, 700), (3, 'Mohan', 'Kumar', 3000, 300)]
[(1, 'Ram', 'Singh', 2000, 500, 'Ram Singh'), (2, 'Shyam', 'Rawat', 10000, 700, 'Shyam Rawat'), (3, 'Mohan', 'Kumar', 3000, 300, 'Mohan Kumar')]

In [0]:
data =[(1,'Ram','Singh',2000,500),(2,'Shyam','Rawat',10000,700),(3,'Mohan','Kumar',3000,300)]
df= spark.createDataFrame(data,['id','fn','ln'])
# display(df)
rdd1=df.rdd.map(lambda x : x + (x[1] + ' ' + x[2],))
df1 = rdd1.toDF(['id','fn','ln','fullname'])
df1.show()
# df1.select('id','fn','ln','fullname').show()

+---+-----+-----+--------+---+-----------+
| id|   fn|   ln|fullname| _5|         _6|
+---+-----+-----+--------+---+-----------+
|  1|  Ram|Singh|    2000|500|  Ram Singh|
|  2|Shyam|Rawat|   10000|700|Shyam Rawat|
|  3|Mohan|Kumar|    3000|300|Mohan Kumar|
+---+-----+-----+--------+---+-----------+

In [0]:
#43. flatmap: flattens the list /array on top of RDD objects and returns a new RDD
# its not available with dartaframe so for that you can use explode in dataframe
data = [('Ram', 'Singh'), ('Shyam', 'Rawat'), ('Mohan', 'Kumar')]
rdd = spark.sparkContext.parallelize(data)

# Print the original RDD
for item in rdd.collect():
    print(item)

# Flatten the tuples and apply split on each string element
rdd1 = rdd.flatMap(lambda x: [elem for elem in x])

# Print the transformed RDD
for item1 in rdd1.collect():
    print(item1)

('Ram', 'Singh')
('Shyam', 'Rawat')
('Mohan', 'Kumar')
Ram
Singh
Shyam
Rawat
Mohan
Kumar

In [0]:
# 44 : partitionBy ()--partitioned large dataset in to smaller files based on one or multiple columns
data =[(1,'Ram','Singh','Male',2000,500),(2,'Shyamoli','Rawat','Female',10000,700),(3,'Mohani','Kumar','Female',3000,300),(4,'Mohan','Kumar','Male',3000,300)]
df=spark.createDataFrame(data,['id','fname','lname','Gender','salary','bonus'])
display(df)
df.write.parquet(path='/FileStore/team_employee/',mode='overwrite',partitionBy=['Gender'])

id,fname,lname,Gender,salary,bonus
1,Ram,Singh,Male,2000,500
2,Shyamoli,Rawat,Female,10000,700
3,Mohani,Kumar,Female,3000,300
4,Mohan,Kumar,Male,3000,300

In [0]:
df_all=spark.read.parquet(path='/FileStore/team_employee/')
df_male=df_all.filter(df_all.Gender == 'Male')
# df_all.show()
df_male.show()

---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
File <command-3327688588576926>:1
----> 1 df_all=spark.read.parquet(path='/FileStore/team_employee/')
      2 df_male=df_all.filter(df_all.Gender == 'Male')
      3 # df_all.show()

File /databricks/spark/python/pyspark/instrumentation_utils.py:48, in _wrap_function.<locals>.wrapper(*args, **kwargs)
     46 start = time.perf_counter()
     47 try:
---> 48     res = func(*args, **kwargs)
     49     logger.log_success(
     50         module_name, class_name, function_name, time.perf_counter() - start, signature
     51     )
     52     return res

File /databricks/spark/python/pyspark/sql/readwriter.py:533, in DataFrameReader.parquet(self, *paths, **options)
    522 int96RebaseMode = options.get("int96RebaseMode", None)
    523 self._set_opts(
    524     mergeSchema=mergeSchema,
    525     pathGlobFilter=pathGlobFilter,
   (...)
    530     int96RebaseMode=int96RebaseMode,
    531 )
--> 533 return self._df(self._jreader.parquet(_to_seq(self._spark._sc, paths)))

File /databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1321, in JavaMember.__call__(self, *args)
   1315 command = proto.CALL_COMMAND_NAME +\
   1316     self.command_header +\
   1317     args_command +\
   1318     proto.END_COMMAND_PART
   1320 answer = self.gateway_client.send_command(command)
-> 1321 return_value = get_return_value(
   1322     answer, self.gateway_client, self.target_id, self.name)
   1324 for temp_arg in temp_args:
   1325     temp_arg._detach()

File /databricks/spark/python/pyspark/errors/exceptions.py:234, in capture_sql_exception.<locals>.deco(*a, **kw)
    230 converted = convert_exception(e.java_exception)
    231 if not isinstance(converted, UnknownException):
    232     # Hide where the exception came from that shows a non-Pythonic
    233     # JVM exception message.
--> 234     raise converted from None
    235 else:
    236     raise

AnalysisException: Unable to infer schema for Parquet. It must be specified manually.

In [0]:
# from_json() converts json string in to maptype or structtype
# 45:from_json() function : take any json string and convert it in to maptype
# 46: from_json() function : take any json string and convert it in to Structtype
#47 : to_json : convert any column (maptype/structType) to json type
#48 json_tuple : used to extract element /query from json string column and create  as new columns
#49: get_json_object : extract JSON string based on path from json column
#50:date functions in pyspark
# current_date
# date_fromat
# to_date:
# 51: datediff,month_between,add_months,date_add(),year(),month()
# 52: timestamp function  :current_timestamp,to_timestamp,hour,minute,second
# 53:approx_count_distinct,avg(),collect_list,collect_Set,count_distinct,count
# 54 :row_number,rank,dense_rank